package com.google.android.systemui.dagger;

import android.app.WallpaperManager;
import android.content.Context;
import android.content.res.AssetManager;
import android.content.res.Resources;
import android.hardware.display.AmbientDisplayConfiguration;
import android.media.session.MediaSessionManager;
import android.util.DisplayMetrics;
import com.android.systemui.dagger.AndroidInternalsModule;
import com.android.systemui.dagger.FrameworkServicesModule;
import com.android.systemui.dagger.GlobalModule;
import com.android.systemui.unfold.FoldStateProviderModule;
import com.android.systemui.unfold.HingeAngleProviderInternalModule;
import com.android.systemui.unfold.UnfoldRotationProviderInternalModule;
import com.android.systemui.unfold.UnfoldSharedInternalModule;
import com.android.systemui.unfold.UnfoldSharedModule;
import com.android.systemui.unfold.UnfoldTransitionModule;
import com.android.systemui.util.kotlin.GlobalCoroutinesModule;
import com.google.android.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl;
import dagger.internal.DoubleCheck;
import dagger.internal.Preconditions;
import dagger.internal.SingleCheck;
import javax.inject.Provider;

/* compiled from: go/retraceme 2137a22d937c6ed93fd00fd873698000dad14919f0531176a184f8a975d2c6e7 */
public final class DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl {
    public final Provider activityManagerActivityTypeProvider;
    public final AndroidInternalsModule androidInternalsModule;
    public final Provider applicationScopeProvider;
    public final Provider buildInfoProvider;
    public final Context context;
    public final Provider deviceStateManagerFoldProvider;
    public final Provider deviceStateRepositoryImplProvider;
    public final Provider dumpManagerProvider;
    public final DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider executionImplProvider;
    public final Provider factoryProvider;
    public final Provider factoryProvider2;
    public final Provider factoryProvider3;
    public final Provider factoryProvider4;
    public final Provider factoryProvider5;
    public final Provider factoryProvider6;
    public final Provider factoryProvider7;
    public final Provider factoryProvider8;
    public final DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider fixedTimingTransitionProgressProvider;
    public final FoldStateProviderModule foldStateProviderModule;
    public final FrameworkServicesModule frameworkServicesModule;
    public final GlobalCoroutinesModule globalCoroutinesModule;
    public final GlobalModule globalModule;
    public final HingeAngleProviderInternalModule hingeAngleProviderInternalModule;
    public final Boolean instrumentationTest;
    public final Provider lifecycleScreenStatusProvider;
    public final Provider lowLightTransitionCoordinatorProvider;
    public final Provider mainCoroutineContextProvider;
    public final Provider mainDispatcherProvider;
    public final Provider opaEnabledSettingsProvider;
    public final Provider pluginDependencyProvider;
    public final Provider pluginEnablerImplProvider;
    public final Provider provideAccessibilityManagerProvider;
    public final Provider provideActivityManagerProvider;
    public final Provider provideActivityTaskManagerProvider;
    public final Provider provideAlarmManagerProvider;
    public final Provider provideAmbientContextManagerProvider;
    public final DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider provideApplicationContextProvider;
    public final Provider provideAsyncLayoutInflaterProvider;
    public final Provider provideAudioManagerProvider;
    public final Provider provideBgFoldStateProvider;
    public final Provider provideBgLooperProvider;
    public final Provider provideBgRotationChangeProvider;
    public final Provider provideBluetoothAdapterProvider;
    public final Provider provideBluetoothManagerProvider;
    public final Provider provideCameraManagerProvider;
    public final Provider provideCaptioningManagerProvider;
    public final Provider provideCarrierConfigManagerProvider;
    public final Provider provideClipboardManagerProvider;
    public final Provider provideColorDisplayManagerProvider;
    public final Provider provideConnectivityManagagerProvider;
    public final Provider provideContentResolverProvider;
    public final Provider provideCrossWindowBlurListenersProvider;
    public final Provider provideDevicePolicyManagerProvider;
    public final Provider provideDeviceStateManagerProvider;
    public final Provider provideDisplayManagerProvider;
    public final Provider provideDisplaySwitchLatencyLoggerProvider;
    public final Provider provideExecutionProvider;
    public final Provider provideFaceManagerProvider;
    public final Provider provideFoldStateProvider;
    public final Provider provideIActivityManagerProvider;
    public final Provider provideIActivityTaskManagerProvider;
    public final Provider provideIAudioServiceProvider;
    public final Provider provideIBatteryStatsProvider;
    public final Provider provideIDreamManagerProvider;
    public final Provider provideIMediaProjectionManagerProvider;
    public final Provider provideINotificationManagerProvider;
    public final Provider provideIPackageManagerProvider;
    public final Provider provideIStatusBarServiceProvider;
    public final Provider provideIUriGrantsManagerProvider;
    public final Provider provideIVrManagerProvider;
    public final Provider provideIWindowManagerProvider;
    public final Provider provideInputManagerProvider;
    public final Provider provideInputMethodManagerProvider;
    public final Provider provideInteractionJankMonitorProvider;
    public final Provider provideIsTestHarnessProvider;
    public final Provider provideJobSchedulerProvider;
    public final Provider provideKeyguardManagerProvider;
    public final Provider provideLatencyTrackerProvider;
    public final Provider provideLauncherAppsProvider;
    public final Provider provideLockPatternUtilsProvider;
    public final Provider provideMainDelayableExecutorProvider;
    public final Provider provideMainExecutorProvider;
    public final DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider provideMainHandlerProvider;
    public final DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider provideMediaRouter2ManagerProvider;
    public final Provider provideMetricsLoggerProvider;
    public final Provider provideNaturalRotationProgressProvider;
    public final Provider provideNetworkScoreManagerProvider;
    public final Provider provideNotificationManagerCompatProvider;
    public final Provider provideNotificationManagerProvider;
    public final Provider provideOptionalTelecomManagerProvider;
    public final Provider provideOptionalVibratorProvider;
    public final Provider provideOverlayManagerProvider;
    public final Provider providePackageManagerProvider;
    public final Provider providePackageManagerWrapperProvider;
    public final Provider providePermissionManagerProvider;
    public final Provider providePluginInstanceManagerFactoryProvider;
    public final Provider providePowerExemptionManagerProvider;
    public final Provider providePowerManagerProvider;
    public final Provider provideProgressForwarderProvider;
    public final Provider provideRoleManagerProvider;
    public final Provider provideRotationChangeProvider;
    public final Provider provideSafetyCenterManagerProvider;
    public final Provider provideSatelliteManagerProvider;
    public final Provider provideSensorPrivacyManagerProvider;
    public final Provider provideShellProgressProvider;
    public final Provider provideShortcutManagerProvider;
    public final Provider provideSmartspaceManagerProvider;
    public final Provider provideStatsManagerProvider;
    public final Provider provideStatusBarManagerProvider;
    public final Provider provideStatusBarScopedTransitionProvider;
    public final Provider provideStorageManagerProvider;
    public final Provider provideSubscriptionManagerProvider;
    public final Provider provideTelecomManagerProvider;
    public final Provider provideTelephonyManagerProvider;
    public final Provider provideTextClassificationManagerProvider;
    public final Provider provideTrustManagerProvider;
    public final Provider provideUiBackgroundExecutorProvider;
    public final Provider provideUiEventLoggerProvider;
    public final Provider provideUiModeManagerProvider;
    public final Provider provideUnfoldOnlyProvider;
    public final Provider provideUserManagerProvider;
    public final Provider provideVibratorProvider;
    public final Provider provideViewConfigurationProvider;
    public final Provider provideVirtualDeviceManagerProvider;
    public final Provider provideWifiManagerProvider;
    public final Provider provideWindowManagerProvider;
    public final Provider providerLayoutInflaterProvider;
    public final Provider providesBiometricManagerProvider;
    public final Provider providesChoreographerProvider;
    public final Provider providesFingerprintManagerProvider;
    public final Provider providesFoldStateListenerProvider;
    public final Provider providesFoldStateLoggerProvider;
    public final Provider providesFoldStateLoggingProvider;
    public final Provider providesPluginExecutorProvider;
    public final Provider providesPluginInstanceFactoryProvider;
    public final Provider providesPluginManagerProvider;
    public final Provider providesSensorManagerProvider;
    public final Provider qSExpansionPathInterpolatorProvider;
    public final Provider resourceUnfoldTransitionConfigProvider;
    public final Provider screenLifecycleProvider;
    public final DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl sysUIGoogleGlobalRootComponentImpl = this;
    public final Provider systemPropertiesHelperProvider;
    public final Provider tracingCoroutineContextProvider;
    public final Provider uncaughtExceptionPreHandlerManagerProvider;
    public final Provider unfoldBgProgressFlagProvider;
    public final Provider unfoldBgProgressHandlerProvider;
    public final Provider unfoldBgTransitionProgressProvider;
    public final Provider unfoldKeyguardVisibilityManagerImplProvider;
    public final Provider unfoldKeyguardVisibilityProvider;
    public final UnfoldRotationProviderInternalModule unfoldRotationProviderInternalModule;
    public final UnfoldSharedInternalModule unfoldSharedInternalModule;
    public final UnfoldSharedModule unfoldSharedModule;
    public final UnfoldTransitionModule unfoldTransitionModule;
    public final DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider unfoldTransitionProgressForwarderProvider;
    public final Provider unfoldTransitionProgressProvider;

    /* renamed from: -$$Nest$mambientDisplayConfiguration  reason: not valid java name */
    public static AmbientDisplayConfiguration m972$$Nest$mambientDisplayConfiguration(DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl) {
        daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.frameworkServicesModule.getClass();
        return new AmbientDisplayConfiguration(daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.context);
    }

    /* renamed from: -$$Nest$mapplicationAssetManager  reason: not valid java name */
    public static AssetManager m973$$Nest$mapplicationAssetManager(DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl) {
        AssetManager assets = ((Context) daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.provideApplicationContextProvider.get()).getAssets();
        Preconditions.checkNotNullFromProvides(assets);
        return assets;
    }

    /* renamed from: -$$Nest$mdisplayIdInteger  reason: not valid java name */
    public static int m974$$Nest$mdisplayIdInteger(DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl) {
        return daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.context.getDisplayId();
    }

    /* renamed from: -$$Nest$mdisplayMetrics  reason: not valid java name */
    public static DisplayMetrics m975$$Nest$mdisplayMetrics(DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl) {
        daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.globalModule.getClass();
        DisplayMetrics displayMetrics = new DisplayMetrics();
        daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.context.getDisplay().getMetrics(displayMetrics);
        return displayMetrics;
    }

    /* renamed from: -$$Nest$mmainResources  reason: not valid java name */
    public static Resources m976$$Nest$mmainResources(DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl) {
        Resources resources = daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.context.getResources();
        Preconditions.checkNotNullFromProvides(resources);
        return resources;
    }

    /* renamed from: -$$Nest$mmediaSessionManager  reason: not valid java name */
    public static MediaSessionManager m977$$Nest$mmediaSessionManager(DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl) {
        daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.getClass();
        MediaSessionManager mediaSessionManager = (MediaSessionManager) daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.context.getSystemService(MediaSessionManager.class);
        Preconditions.checkNotNullFromProvides(mediaSessionManager);
        return mediaSessionManager;
    }

    /* renamed from: -$$Nest$mwallpaperManager  reason: not valid java name */
    public static WallpaperManager m978$$Nest$mwallpaperManager(DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl) {
        daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.getClass();
        WallpaperManager wallpaperManager = (WallpaperManager) daggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl.context.getSystemService(WallpaperManager.class);
        Preconditions.checkNotNullFromProvides(wallpaperManager);
        return wallpaperManager;
    }

    public DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleGlobalRootComponentImpl(GlobalModule globalModule2, AndroidInternalsModule androidInternalsModule2, FrameworkServicesModule frameworkServicesModule2, GlobalCoroutinesModule globalCoroutinesModule2, UnfoldTransitionModule unfoldTransitionModule2, UnfoldSharedModule unfoldSharedModule2, UnfoldSharedInternalModule unfoldSharedInternalModule2, UnfoldRotationProviderInternalModule unfoldRotationProviderInternalModule2, HingeAngleProviderInternalModule hingeAngleProviderInternalModule2, FoldStateProviderModule foldStateProviderModule2, Context context2, Boolean bool) {
        this.instrumentationTest = bool;
        this.context = context2;
        this.unfoldTransitionModule = unfoldTransitionModule2;
        this.unfoldSharedInternalModule = unfoldSharedInternalModule2;
        this.foldStateProviderModule = foldStateProviderModule2;
        this.unfoldSharedModule = unfoldSharedModule2;
        this.hingeAngleProviderInternalModule = hingeAngleProviderInternalModule2;
        this.unfoldRotationProviderInternalModule = unfoldRotationProviderInternalModule2;
        this.globalModule = globalModule2;
        this.globalCoroutinesModule = globalCoroutinesModule2;
        this.frameworkServicesModule = frameworkServicesModule2;
        this.androidInternalsModule = androidInternalsModule2;
        this.systemPropertiesHelperProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 0);
        this.provideIWindowManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 1);
        this.provideAccessibilityManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 2);
        this.resourceUnfoldTransitionConfigProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 4);
        this.provideDeviceStateManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 6);
        this.deviceStateManagerFoldProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 5);
        this.provideContentResolverProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 9);
        this.factoryProvider = SingleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(8, 1, this));
        this.factoryProvider2 = SingleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(10, 1, this));
        this.factoryProvider3 = SingleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(12, 1, this));
        this.factoryProvider4 = SingleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(11, 1, this));
        this.dumpManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 18);
        this.screenLifecycleProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 17);
        this.lifecycleScreenStatusProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 16);
        this.provideActivityManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 20);
        this.activityManagerActivityTypeProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 19);
        this.unfoldKeyguardVisibilityManagerImplProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 22);
        this.unfoldKeyguardVisibilityProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 21);
        this.factoryProvider5 = SingleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(15, 1, this));
        this.provideMainHandlerProvider = new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(23, 1, this);
        this.providesSensorManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 25);
        this.provideUiBackgroundExecutorProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 26);
        this.factoryProvider6 = SingleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(24, 1, this));
        this.provideDisplayManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 29);
        this.factoryProvider7 = SingleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(28, 1, this));
        this.provideRotationChangeProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 27);
        this.provideFoldStateProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 14);
        this.fixedTimingTransitionProgressProvider = new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(13, 1, this);
        this.factoryProvider8 = SingleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(30, 1, this));
        this.provideBgLooperProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 34);
        this.unfoldBgProgressHandlerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 33);
        this.provideBgRotationChangeProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 35);
        this.provideBgFoldStateProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 32);
        this.unfoldBgTransitionProgressProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 31);
        this.unfoldBgProgressFlagProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 36);
        this.unfoldTransitionProgressProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 7);
        this.provideMainExecutorProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 38);
        this.provideUnfoldOnlyProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 37);
        this.provideShellProgressProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 3);
        this.provideUiEventLoggerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 39);
        this.provideActivityTaskManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 40);
        this.provideWindowManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 41);
        this.provideIStatusBarServiceProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 42);
        this.provideUserManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 43);
        this.provideLauncherAppsProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 44);
        this.provideInteractionJankMonitorProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 45);
        this.providePackageManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 46);
        this.provideApplicationContextProvider = new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(47, 1, this);
        this.provideIsTestHarnessProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 48);
        this.providePowerManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 49);
        this.tracingCoroutineContextProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 52);
        this.mainCoroutineContextProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 51);
        this.applicationScopeProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 50);
        this.provideAlarmManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 53);
        this.providesFoldStateListenerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 54);
        this.buildInfoProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 55);
        this.provideExecutionProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(56, 1, this));
        this.providesFingerprintManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 57);
        this.provideFaceManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 58);
        this.providerLayoutInflaterProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 59);
        this.provideMainDelayableExecutorProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 60);
        this.provideLockPatternUtilsProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 61);
        this.provideTelephonyManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 62);
        this.provideLatencyTrackerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 63);
        this.mainDispatcherProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 64);
        this.provideTrustManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 65);
        this.provideSubscriptionManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 66);
        this.provideIDreamManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 67);
        this.provideDevicePolicyManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 68);
        this.provideSensorPrivacyManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 69);
        this.providesBiometricManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 70);
        this.provideIActivityTaskManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 71);
        this.providesPluginExecutorProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 74);
        this.provideNotificationManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 75);
        this.pluginEnablerImplProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 76);
        this.providesPluginInstanceFactoryProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 77);
        this.providePluginInstanceManagerFactoryProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 73);
        this.uncaughtExceptionPreHandlerManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 78);
        this.providesPluginManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 72);
        this.provideMetricsLoggerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 79);
        this.provideViewConfigurationProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 80);
        this.provideIActivityManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 81);
        this.providesChoreographerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 82);
        this.provideConnectivityManagagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 83);
        this.provideWifiManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 84);
        this.provideCarrierConfigManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 85);
        this.provideCameraManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 86);
        this.provideSatelliteManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 87);
        this.provideIBatteryStatsProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 88);
        this.providePackageManagerWrapperProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 89);
        this.provideMediaRouter2ManagerProvider = new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(90, 1, this);
        this.provideSmartspaceManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 91);
        this.provideAudioManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 92);
        this.provideVirtualDeviceManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 93);
        this.provideNaturalRotationProgressProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 94);
        this.provideStatusBarScopedTransitionProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 95);
        this.provideNetworkScoreManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 96);
        this.provideInputMethodManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 97);
        this.provideTelecomManagerProvider = DaggerSysUIGoogleGlobalRootComponent$WMComponentImpl$$ExternalSyntheticOutline0.m(this, 98);
        this.providePowerExemptionManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(99, 1, this));
        this.provideKeyguardManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(100, 1, this));
        this.provideVibratorProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(101, 1, this));
        this.provideRoleManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(102, 1, this));
        this.provideShortcutManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(103, 1, this));
        this.provideInputManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(104, 1, this));
        this.provideBluetoothManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(106, 1, this));
        this.provideBluetoothAdapterProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(105, 1, this));
        this.provideINotificationManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(107, 1, this));
        this.provideCrossWindowBlurListenersProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(108, 1, this));
        this.provideJobSchedulerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(109, 1, this));
        this.opaEnabledSettingsProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(110, 1, this));
        this.providePermissionManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(111, 1, this));
        this.provideSafetyCenterManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(112, 1, this));
        this.provideIMediaProjectionManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(113, 1, this));
        this.provideIAudioServiceProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(114, 1, this));
        this.pluginDependencyProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(115, 1, this));
        this.provideOptionalVibratorProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(116, 1, this));
        this.provideUiModeManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(117, 1, this));
        this.provideIUriGrantsManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(118, 1, this));
        this.provideColorDisplayManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(119, 1, this));
        this.provideOverlayManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(120, 1, this));
        this.unfoldTransitionProgressForwarderProvider = new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(122, 1, this);
        this.provideProgressForwarderProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(121, 1, this));
        this.provideStatusBarManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(123, 1, this));
        this.provideIVrManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(124, 1, this));
        this.lowLightTransitionCoordinatorProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(125, 1, this));
        this.provideTextClassificationManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(126, 1, this));
        this.provideClipboardManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(127, 1, this));
        this.provideDisplaySwitchLatencyLoggerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(128, 1, this));
        this.provideStorageManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(129, 1, this));
        this.provideNotificationManagerCompatProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(130, 1, this));
        this.provideAmbientContextManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(131, 1, this));
        this.provideStatsManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(132, 1, this));
        this.providesFoldStateLoggingProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(133, 1, this));
        this.providesFoldStateLoggerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(134, 1, this));
        this.deviceStateRepositoryImplProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(135, 1, this));
        DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(136, 1, this));
        this.qSExpansionPathInterpolatorProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(137, 1, this));
        this.provideIPackageManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(138, 1, this));
        this.provideOptionalTelecomManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(139, 1, this));
        this.provideAsyncLayoutInflaterProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(140, 1, this));
        this.provideCaptioningManagerProvider = DoubleCheck.provider(new DaggerSysUIGoogleGlobalRootComponent$KeyguardStatusBarViewComponentImpl.SwitchingProvider(141, 1, this));
    }
}
