package com.google.android.systemui.power;

import com.android.internal.logging.UiEventLogger;

/* compiled from: go/retraceme db998610a30546cfb750cb42d68186f67be36966c6ca98c5d0200b062af37cac */
enum BatteryMetricEvent implements UiEventLogger.UiEventEnum {
    BATTERY_DEFENDER_NOTIFICATION(876),
    BATTERY_DEFENDER_BYPASS_LIMIT(877),
    BATTERY_DEFENDER_BYPASS_LIMIT_FOR_TIPS(878),
    DELETE_BATTERY_DEFENDER_NOTIFICATION(1273),
    ADAPTIVE_CHARGING_NOTIFICATION(1274),
    DELETE_ADAPTIVE_CHARGING_NOTIFICATION(1275),
    ADAPTIVE_CHARGING_NOTIFICATION_BYPASS(1346),
    SEND_INCOMPATIBLE_CHARGING_NOTIFICATION(1271),
    DELETE_INCOMPATIBLE_CHARGING_NOTIFICATION(1272),
    SEVERE_BATTERY_DIALOG(991),
    SEVERE_BATTERY_DIALOG_TURN_ON(992),
    SEVERE_BATTERY_DIALOG_CANCEL(993),
    SAVER_CONFIRMATION_DIALOG(1347),
    SAVER_CONFIRMATION_DIALOG_TURN_ON(1348),
    SAVER_CONFIRMATION_DIALOG_CANCEL(1349),
    SAVER_CONFIRMATION_DIALOG_SETUP(1350),
    EXTREME_LOW_BATTERY_NOTIFICATION(1351),
    BATTERY_SAVER_ENABLED(1359),
    BATTERY_SAVER_ENABLED_REASON(1360),
    BATTERY_SAVER_DISABLED(1372),
    BATTERY_SAVER_DISABLED_REASON(1373);
    
    private final int mId;

    /* access modifiers changed from: public */
    BatteryMetricEvent(int i) {
        this.mId = i;
    }

    public final int getId() {
        return this.mId;
    }
}
